- id: 0
- id: 1
  name: Audeze LCD-3 Over Ear Headphones Fazor Elements
  short-name: Audeze LCD-3
  imgs: [ "udeze-lcd-3-over.jpg" ]
  asin: B00O12MH1S
  brand: Audeze
- id: 2
  name: Yamaha P45 - Digital Piano
  short-name: Yamaha P-45B
  imgs: [ "yamaha-p45-88-key.jpg" ]
  asin: B00UJ9LNDK
  brand: Yamaha
- id: 3
  name: Audeze Mobius Premium 3D Gaming Headset with Surround Sound
  short-name: Audeze Mobius headset
  imgs: [ "audeze-mobius-premium-3d.jpg" ]
  asin: B07BDQZ52Z
  brand: Audeze
- id: 3.1
  name: Nuraphone - Wireless Bluetooth Over Ear Headphones With Earbuds
  short-name: Nuraphone Wireless Headphones
  imgs: [ "nuraphone-wireless-over-the.jpg" ]
  asin: B076X4KH11
  brand: Nuraphone
- id: 4
  name: Ruputas Wowstick 1F+ Electric Screwdriver and Repair Kit
  short-name: Ruputas Wowstick 1F+
  imgs: [ "ruputas-wowstick-1f-electric.jpg" ]
  asin: B076X4KH11
  brand: Ruputas
- id: 5
  name: iFixit Pro Tech Toolkit - Electronics, Smartphone, Computer & Tablet Repair Kit
  short-name: iFixit Pro Tech Toolkit
  imgs: [ ]
  asin: B01GF0KV6G
  brand: iFixit
- id: 6
  name: Bang & Olufsen B&O Play H8i
  short-name: B&O Beoplay H8i
  imgs: [ "bang-and-olufsen-play.jpg" ]
  asin: B078HPHLPR
  brand: Bang & Olufsen
- id: 7
  name: Neato Robotics D7 Connected Laser Guided Smart Robot Vacuum
  short-name: Neato Robotics D7
  imgs: [ "neato-robotics-d7-robot.jpg" ]
  asin: B078MPFN55
  brand: Neato Robotics
- id: 8
  name: Apple iMac 27-inch Retina 5K
  short-name: iMac Retina 5K
  imgs: [ "apple-imac-27-inch.jpg" ]
  asin: B07Q1NBCVB
  brand: Apple
- id: 9
  name: Audeze LCD-4 Over Ear Headphones
  short-name: Audeze LCD-4
  imgs: [ "audeze-lcd-4-over.jpg" ]
  asin: B01DTQ6AMS
  brand: Audeze
- id: 10
  name: Audeze LCD-3 Over Ear Headphones Fazor Elements MAPLE WOOD VERSION
  short-name: Audeze LCD-3
  imgs: [ "audeze-lcd-3-wood.jpg" ]
  asin: B07D9WWKTS
  brand: Audeze
- id: 11
  name: HIFIMAN HE1000 V2 Over Ear Headphones
  short-name: HIFIMAN HE1000 V2
  imgs: [ "hifiman-he1000-v2-over.jpg" ]
  asin: B01I50644C
  brand: HIFIMAN
- id: 12
  name: iRobot Roomba 980 Robot Vacuum
  short-name: iRobot Roomba 980
  imgs: [ "irobot-roomba-980-robot.jpg" ]
  asin: B013E9L4ZS
  brand: iRobot
- id: 13
  name: Acer Predator Helios 300 Gaming Laptop
  short-name: Acer Preditor helios 300
  imgs: [ "acer-predator-helios-300.jpg" ]
  asin: B07CTHLX8C
  brand: Acer
- id: 14
  name: 2019 HP Premium HD Laptop
  short-name: 2019 HP Premium HD Laptop
  imgs: [ "hp-premium-hd-laptop.jpg" ]
  asin: B07QKWTZ4B
  brand: HP
- id: 15
  name: Canon EOS Rebel T6 Digital SLR Camera Kit with EF-S 18-55mm f/3.5-5.6 IS II Lens (Black)
  short-name: Canon EOS Rebel T6
  imgs: [ "canon-eos-rebel-t6.jpg" ]
  asin: B01CO2JPYS
  brand: Canon
- id: 16
  name: Arsvita Car Audio Bluetooth Cassette Receiver
  short-name: Arsvita Car Audio Bluetooth Cassette Receiver
  imgs: [ "arsvita-car-audio-bluetooth.jpg" ]
  asin: B07QSW6KNY
  brand: Arsvita
- id: 17
  name: MSI GeForce GTX 1080
  short-name: MSI Geforce GTX 1080
  imgs: [ "msi-geforce-gtx-1080.jpg" ]
  asin: B01HHBQBLG
  brand: MSI
- id: 18
  name: Concept2 Model D Indoor Rowing Machine
  short-name: Concept2 Rowing Machine
  imgs: [ "concept2-model-d-indoor.jpg" ]
  asin: B00NH9WEUA
  brand: Concept2
- id: 19
  name: CyberpowerPC Gamer Xtreme VR Gaming PC
  short-name: CyberpowerPC Gamer Xtreme VR Gaming PC
  imgs: [ "cyberpowerpc-gamer-xtreme-vr.jpg" ]
  asin: B07PKXQBHN
  brand: CyberpowerPC
- id: 20
  name: Doona Infant Car Seat & Latch Base
  short-name: Doona Infant car seat
  imgs: [ "doona-infant-car-seat.jpg" ]
  asin: B07HML1BT5
  brand: 
- id: 21
  name: NETGEAR Nighthawk Smart WIFI Router
  short-name: NETGEAR Nighthawk WIFI Router
  imgs: [ "netgear-nighthawk-smart-wifi.jpg" ]
  asin: B07C65K9H9
- id: 22
  name: NordicTrack T Series 6.5S and 6.5Si Treadmill
  short-name: NordicTrack T Series
  imgs: [ "nordictrack-tseries-65s-65si.jpg" ]
  asin: B0193V3DJ6
- id: 23
  name: Oculus Rift S PC-Powered VR Gaming Headset
  short-name: Oculus Rift S
  imgs: [ "oculus-rift-s-pc.jpg" ]
  asin: B07PTMKYS7
  brand: Oculus
- id: 24
  name: SimpliSafe 12- Piece Home Security System with HD Camera and Smoke Detector
  short-name: SimpliSafe Home Security System
  imgs: [ "simplisafe-12-piece-home.jpg" ]
  asin: B07C4WT5LQ
  brand: SimpliSafe
- id: 25
  name: MDMA Therapy Home Kit For Cat Depression
  short-name: ""
  imgs: [ "mdma-cat-depression-therapy.jpg" ]
  brand: MDMA
- id: 26
  name: Destroy the Amazon rainforest for charity with Amazonian wood clothing
  short-name: ""
  imgs: [ "amazon-wood-clothing-review.jpg" ]
  brand: rainforest
- id: 27
  name: Audeze LCD-X Over Ear Open Back Headphone with New Suspension Headband Creator Package – no Travel case
  short-name: Audeze LCD-X
  imgs: [ "audeze-lcd-x-over.jpg" ]
  asin: B0765KJ5CB
  brand: Audeze
- id: 28
  name: DELONGHI ESAM3300 Super Automatic Espresso/Coffee Machine
  short-name: DELONGHI ESAM3300
  imgs: [ "elonghi-ESAM3300-super-automatic.jpg" ]
  asin: B000N2YKQ0
  brand: DELONGHI
- id: 29
  name: GoWISE USA 8-Quart 8-in-1 Electric Pressure Cooker/Slow Cooker
  short-name: GoWISE 8-in-1 Cooker
  imgs: [ "gowise-usa-8-quart.jpg" ]
  asin: B00GTU2UQM
  brand: GoWISE
- id: 30
  name: The New Darkphone by DarkWeb
  short-name: DarkWeb Darkphone
  imgs: [ "the-new-darkweb-darkphone.jpg"]
  brand: Darkweb
- id: 31
  name: V-MODA XFBT2-MBLACK Crossfade 2 Wireless Over-Ear Headphones
  short-name: V-MODA Headphones
  imgs: [ "vmoda-crossfade-2-wireless.jpg" ]
  brand: V-MODA
- id: 32
  name: Bose A20 Aviation Headset with Bluetooth Dual Plug Cable, Black
  short-name: Bose A20 Aviation Headset
  imgs: [ "Bose-A20-Aviation-Headset-with-Bluetooth.jpg" ]
  asin: B010FTYIUS
  brand: Bose
- id: 33
  name: Dyson Supersonic Hair Dryer
  short-name: Dyson Supersonic Hair Dryer
  imgs: [ "Dyson-Supersonic-Hair-Dryer-Review.jpg" ]
  asin: B01F6XZ6BS
  brand: Dyson
- id: 34
  name: Parrot PF728000 Anafi Drone, Foldable Quadcopter Drone with 4K HDR Camera
  short-name: Parrot PF728000 Anafi Drone
  imgs: [ "Parrot-PF728000-Anafi-Drone.jpg" ]
  asin: B07D5R2JKL
  brand: Parrot
- id: 35
  name: Nintendo Switch – Neon Red and Neon Blue Joy-Con - HAC 001
  short-name: Nintendo Switch
  imgs: [ "Nintendo-Switch–Neon-Red-and-Neon-Blue.jpg" ]
  asin: B01MUAGZ49
  brand: Nintendo
- id: 36
  name: XtremepowerUS Mini Pocket Motorcycle Gasoline Bike Motorcycle
  short-name: XtremepowerUS Mini Pocket Motorcycle
  imgs: [ "XtremepowerUS-Mini-Pocket-Motorcycle-Powered-by-Gasoline.jpg" ]
  asin: B075B1BM7M
  brand: XtremepowerUS
- id: 37
  name: Braun Series 9 Men's Electric Foil Shaver with Wet & Dry Integrated Precision Trimmer & Rechargeable and Cordless Razor
  short-name: Braun Series 9 Men's Electric Foil Shaver
  imgs: [ "Braun-Series-9-Mens-Electric-Foil-Shaver.jpg" ]
  asin: B07F7XYMNN
  brand: Braun
- id: 38
  name: Segway Ninebot ES2 Folding Electric Kick Scooter
  short-name: Segway Ninebot ES2 Electric Scooter
  imgs: [ "Segway-Ninebot-ES2-Folding-Electric-Kick-Scooter.jpg" ]
  asin: B07H8T9K9J
  brand: Segway
- id: 39
  name: HP Pavilion 24-Inch All-in-One Computer
  short-name: HP 24-Inch All-in-One Computer
  imgs: [ "HP-Pavilion-24-Inch-All-in-One-Computer.jpg" ]
  asin: B07SGH132Y
  brand: HP
- id: 40
  name: DHP Studio Loft Bunk Bed Over Desk and Bookcase
  short-name: DHP Studio Loft Bunk Bed
  imgs: [ "DHP-Studio-Loft-Bunk-Bed-Over-Desk-and-Bookcase.jpg" ]
  asin: B07K4424RZ
  brand: DHP
- id: 41
  name: HP Pavilion 590 Desktop Computer
  short-name: HP 590 Desktop Computer
  imgs: [ "HP-Pavilion-Desktop-Computer.jpg" ]
  asin: B07MDYZW37
  brand: HP
- id: 42
  name: Alienware M15 Thin and Light 15 Gaming Laptop
  short-name: Alienware M15 Gaming Laptop
  imgs: [ "Alienware-M15-Gaming-Laptop.jpg" ]
  asin: B07MP4LK82
  brand: Alienware
- id: 43
  name: Pimax 5K Plus Virtual Reality Headset
  short-name: Pimax 5k plus VR Headset
  imgs: [ "Pimax-Virtual-Reality-Headset.jpg" ]
  asin: B07JZL5QK3
  brand: Pimax
- id: 44
  name: Bose SoundTouch 30 Wireless Speakers
  short-name: Bose SoundTouch 30 Speakers
  imgs: [ "Bose-SoundTouch-Wireless-Speakers.jpg" ]
  asin: B011IKGT46
  brand: Bose
- id: 45
  name: Lenovo Flex 14 2-in-1 Convertible Laptop
  short-name: Lenovo Flex Convertible Laptop
  imgs: [ "Lenovo-Flex-Convertible-Laptop.jpg" ]
  asin: B07PB5M8DS
  brand: Lenovo
- id: 46
  name: P.MAI Premium Leather Laptop Backpack with Wristlet
  short-name: P.MAI Premium Leather Laptop Bag
  imgs: [ "P.MAI-Premium-Leather-Backpack.jpg" ]
  asin: B01DPNMCGI
  brand: P.MAI
- id: 47
  name: Tufts and Needle Queen Mattress
  short-name: Tufts and Needle 
  imgs: [ "Tufts-and-Needle-Queen-Mattress.jpg" ]
  asin: B00QBZ265U
  brand: Tufts
- id: 48
  name: Garmin Forerunner 645 Music and GPS Running Watch
  short-name: Garmin Forerunner GPS Running Watch
  imgs: [ "Garmin-Forerunner-GPS-Running-Watch.jpg" ]
  asin: B078H244WN
  brand: Garmin
- id: 49
  name: Zivix Jamstik+
  short-name: Jamstik+
  imgs: [ "Zivix-Jamstik.jpg" ]
  asin: B0149YRRXA
  brand: Zivix
- id: 50
  name: The new SoftWeaponry Baby Taser
  imgs: [ "baby-taser.jpg" ]
  brand: SoftWeaponry
- id: 51 
  name: Real Life Joker Costume
  imgs: [ "real-life-joker-costume.jpg" ]
  brand: Costume & Customs
- id: 52
  name: Facebook Voting Machines
  imgs: [ "facebook-voting-machines.jpg" ]
  brand: Nootrusha
- id: 53
  name: EVGA GeForce RTX 2080
  short-name: GeForce RTX 2080
  imgs: [ "EVGA-GeForce.jpg" ]
  asin: B07N889XT8
- id: 54
  name: Razer Huntsman Elite Gaming
  short-name: Razer Huntsman Elite
  imgs: [ "Razer-Huntsman.jpg" ]
  asin: B07DHNX18W
- id: 55
  name: Razer Phone 2
  short-name: Razer Phone
  imgs: [ "Razer-phone.jpg" ]
  asin: B07H9V6PHZ
- id: 56
  name: Apple Watch Series 5
  short-name: Apple Watch
  imgs: [ "Apple-Watch.jpg" ]
  asin: B07XQSJ7Q5
- id: 57
  name: Acer Aspire 5
  short-name: Acer Aspire 
  imgs: [ "Acer-Aspire.jpg" ]
  asin: B07RF1XD36
- id: 58
  name:  DJI Spark Remote Control Combo
  short-name:  DJI Spark  
  imgs: [ "DJI-Spark.jpg" ]
  asin: B075TDRS2M
- id: 59
  name:  Gravity Blanket
  short-name:  Gravity Blanket
  imgs: [ "Gravity-Blanket.jpg" ]
  asin: B07BN75Z3R
- id: 60
  name:  Dell Inspiron 14 2-in-1 laptop
  short-name:  Dell Inspiron 14 
  imgs: [ "Dell-Inspiron.jpg" ]
  asin: B07KY83DPV
- id: 61
  name:  Oculus Quest
  short-name:  Oculus  
  imgs: [ "Oculus-Quest.jpg" ]
  asin: B07HNW68ZC
- id: 62
  name:  Blendtec Total Classic Original Blender with Wildside+ Jar
  short-name:  Blendtec Total Classic Blender 
  imgs: [ "Blendtec-Total-Classic.jpg" ]
  asin: B07N3C6V5G
- id: 63
  name:  Powerbeats Pro Totally Wireless Headphones
  short-name:  Powerbeats Pro headphones 
  imgs: [ "Powerbeats-Pro.jpg" ]
  asin: B07R5QD598
- id: 64
  name:  Aera Smart Diffuser
  short-name:  Aera Diffuser 
  imgs: [ "Aera-Smart-Diffuser.jpg" ]
  asin: B071JSCCBG
- id: 65
  name:  Echo Show
  short-name:  Echo Show
  imgs: [ "Echo-Show.jpg" ]
  asin: B077SXWSRP
- id: 66
  name:  Ember Temperature Control Smart Mug
  short-name:  Ember Smart Mug
  imgs: [ "Ember-Smart-Mug.jpg" ]
  asin: B07Z5H4TF5
- id: 67
  name:  Kindle paperwhite
  short-name:  Kindle 
  imgs: [ "Kindle-paperwhite.jpg" ]
  asin: B07745PV5G
- id: 68
  name:  23andMe
  short-name:  23andMe
  imgs: [ "23andMe.jpg" ]
  asin: B01G7PYQTM
- id: 69
  name:  Dash Rapid Egg Cooker
  short-name:  Dash Egg Cooker
  imgs: [ "Dash-Egg-Cooker.jpg" ]
  asin: B00DDXWFY0
- id: 70
  name:  Rocketbook Wave Smart Notebook
  short-name:  Rocketbook 
  imgs: [ "Rocketbook-Smart-Notebook.jpg" ]
  asin: B01GU6TINM
- id: 71
  name:  Linenspa Memory Foam and Innerspring Hybrid Mattress
  short-name:  Linenspa Hybrid Mattress 
  imgs: [ "Linenspa-Hybrid-Mattress.jpg" ]
  asin: B07HN7VWFK
- id: 72
  name:  Huion KAMVAS GT-191
  short-name:  Huion  
  imgs: [ "Huion-KAMVAS.jpg" ]
  asin: B072N2C2PB
- id: 73
  name: Beats EP On-Ear Headphones
  short-name: Beats EP Headphones
  imgs: [ "Beats-EP-Headphones.jpg" ]
  asin: B01LX8OJMT
- id: 74
  name:  ICEWATER 3 in 1 Water Bottle
  short-name:  ICEWATER 3 in 1 bottle  
  imgs: [ "ICEWATER-Water-Bottle.jpg" ]
  asin: B07KW6GH6Y
- id: 75
  name:  PhoneSoap 3 UV Smartphone Sanitizer
  short-name:  PhoneSoap 3 UV   
  imgs: [ "PhoneSoap-3-UV.jpg" ]
  asin: B072R6MJKQ
- id: 76
  name:  AeroGarden Bounty
  short-name:  AeroGarden Bounty Basic  
  imgs: [ "AeroGarden-Bounty.jpg" ]
  asin: B07TDVG5L6
- id: 77
  name:  Dyson Pure Cool
  short-name:  Pure Cool
  imgs: [ "Dyson-Pure.jpg" ]
  asin: B071HMNTPM
- id: 78
  name:  Kempf Go Away Doormat
  short-name:  Kempf Doormat  
  imgs: [ "Kempf-Doormat.jpg" ]
  asin: B000I1UYXO
- id: 79
  name:  Levitating Fern
  short-name:  Fern  
  imgs: [ "Levitating-Fern.jpg" ]
  asin: B075RRZS3G
- id: 80
  name:  Skatecycle
  short-name:  Skatecycle  
  imgs: [ "Skatecycle.jpg" ]
  asin: B009D1LQRS
- id: 81
  name:  The World’s Smartest Indoor Garden By Click & Grow
  short-name:  World’s Smartest Indoor Garden  
  imgs: [ "Smartest-Indoor-Garden.jpg" ]
  asin: B075QQ4SL8
- id: 82
  name:  Lightahead LED Mini Desktop Jellyfish Lamp
  short-name:  Lightahead Jellyfish Lamp  
  imgs: [ "Lightahead-Jellyfish-Lamp.jpg" ]
  asin: B075314RH2
- id: 83
  name:  Masdio by Ampulla Bedside Lamp
  short-name:  Masdio lamp  
  imgs: [ "Masdio-lamp.jpg" ]
  asin: B076Y5X97Y
- id: 84
  name:  ZippyPaws Woodland Friends Burrow
  short-name:  ZippyPaws Woodland Friends  
  imgs: [ "ZippyPaws-Woodland-Friends.jpg" ]
  asin: B008PFB3HG
- id: 85
  name:  Jalousie 12 Pack Dog Squeaky Toys
  short-name:  Jalousie 12 Pack Dog Toys  
  imgs: [ "Jalousie-Dog-Toys.jpg" ]
  asin: B07CSG684C
- id: 86
  name:  DOG CARE Bark Collar
  short-name:  DOG CARE  
  imgs: [ "DOG-CARE.jpg" ]
  asin: B07SR83Y1W
- id: 87
  name:  Ottoson Outward Hound Brick Puzzle
  short-name:  Outward Hound  
  imgs: [ "Outward-Hound.jpg" ]
  asin: B0711Y9XTF
- id: 88
  name:  PUPTECK Dog Chew Rope Toy
  short-name:  PUPTECK Chew Toy  
  imgs: [ "PUPTECK-Chew-Toy.jpg" ]
  asin: B07ZR955FL
- id: 89
  name:  VARRAM Pet Fitness Robot
  short-name:  VARRAM Fitness Robot  
  imgs: [ "VARRAM-Fitness-Robot.jpg" ]
  asin: B07RRD3JGQ
- id: 90
  name:  Asus C223NA-DH02-RD Chromebook 11.6"
  short-name:  Asus Chromebook 12  
  imgs: [ "Asus-Chromebook.jpg" ]
  asin: B07H5B75SY
- id: 91
  name:  FUZZU Dog Toy With Squeaker
  short-name:  FUZZU Dog Toy  
  imgs: [ "FUZZU-Dog-Toy.jpg" ]
  asin: B01ICEDPMU
- id: 92
  name:  Samsung Galaxy Watch Active2
  short-name:  Samsung   
  imgs: [ "Samsung-Galaxy-Watch.jpg" ]
  asin: B07YNTSSP6
